apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: your-roll-number/web-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production
