global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics'  
    static_configs:
      - targets: ['web-app-service:5000']  
        labels:
          app: 'flask-web-app'

